---
- name: Démarrer MariaDB (pas systemd)
  shell: "{{ mariadb_start_command }}"
  async: 0
  poll: 0
  changed_when: false

- name: Pause pour laisser MariaDB démarrer
  pause:
    seconds: 10

- name: Tester si root a un mot de passe défini (connexion via socket sans mot de passe)
  shell: >
    mysql --protocol=socket -uroot --socket=/run/mysqld/mysqld.sock -e "SELECT 1;"
  register: root_pass_check
  ignore_errors: true
  changed_when: false

- name: Configurer le mot de passe root MariaDB (Debian/Ubuntu)
  mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    user: root
    password: "{{ mariadb_root_password }}"
    host: localhost
  become: true
  when: root_pass_check.rc == 0 and ansible_os_family == "Debian"

- name: Configurer le mot de passe root MariaDB (Rocky Linux)
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    user: root
    password: "{{ mariadb_root_password }}"
    host: localhost
  become: true
  when: ansible_os_family == "RedHat"

- name: Sécuriser MariaDB en supprimant utilisateurs anonymes et base test
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: ""
    host_all: yes
    state: absent

- name: Supprimer les utilisateurs anonymes
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    user: ""
    host_all: true
    state: absent

- name: Supprimer la base de test par défaut
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: test`
    state: absent

- name: Créer base WordPress
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: "{{ wordpress_db_name }}"
    state: present

- name: Créer utilisateur WordPress
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    host: localhost
    state: present
